language: bash
os: osx
osx_image: xcode7.3

addons:
  homebrew:
    taps:
      - homebrew/dupes
    packages:
      - php@5.6
      - php@7.1
      - php@7.2
      - php@7.3
    update: true

install:
  - ./.travis/install.sh

script:
  - ./.travis/clean.sh
  - ./.travis/test.sh
