language: bash
os: osx
matrix:
    include:
        - osx_image: xcode7.3
        - osx_image: xcode8
        - osx_image: xcode8.1
        - osx_image: xcode8.2
        - osx_image: xcode8.3
        - osx_image: xcode9

before_install:
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew tap homebrew/homebrew-php
  - brew update

install:
  - ./.travis/install.sh

script:
  - ./.travis/clean.sh
  - ./.travis/test.sh
